### ISSUE TITLE
How to use the patch? 

### ISSUE THREAD

**Issue by CodeZ1LLa** [fantacinni/cpuminer#1]
Hi! I can't find anything about how to use it. Should I replace a part of the code, or copy the file replacing the original one? 
Thanks!

**Comment by fantacinni** [comment]
I don't use cpuminer_gr any more and you may try if it still works or not.
Download this patch and run the following command in cpuminer source code root folder.
$ git apply no_dev_fee.patch

**Comment by CodeZ1LLa** [comment]
Thank you! I'll try
